Refactor all shell scripts
- fix faulty quoting
- Use `-eu` mode everywhere
- Consistent error messages
- Consistent usage text
- Removed unused scripts
- Moved some scripts around

diff --git a/bin/askpass b/bin/askpass
--- a/bin/askpass
+++ b/bin/askpass
@@ -1,22 +1,22 @@
 #!/usr/bin/env bash
 # SSH_ASKPASS handler that uses `pass` to autofill SSH key passwords.
 
+set -euo pipefail
+
 if echo "$1" | grep -q -e "Enter passphrase for"; then
-	if [[ "$1" =~ \'(.+)\' ]]; then
+  if [[ "$1" =~ \'(.+)\' ]]; then
     path="${BASH_REMATCH[1]}"
-	fi
+  fi
 
-	if [ -n "$path" ]; then
-		key="$(basename "$path" .${path##*.})"
-	else
-		echo "askpass: key path could not be identified." >&2
-		echo "[ssh] $1"
-		read -r CHOICE
-		echo "$CHOICE"
-	fi
-
-	pass "ssh/$key"
+  if [ -n "${path:-}" ]; then
+    key="$(basename "$path" .${path##*.})"
+    pass "ssh/$key"
+  else
+    echo "askpass: key path could not be identified." >&2
+    printf '[ssh] %s\n' "$1" >&2
+    read -r CHOICE
+    echo "$CHOICE"
+  fi
 else
-	exit 1
+  exit 1
 fi
-
diff --git a/bin/required b/bin/required
--- a/bin/required
+++ b/bin/required
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/sh -eu
 # Checks if a program is installed.
 
-has "$1" || err "$1 is required but not installed. Aborting."
+has "$1" || err "$1 is required but not installed"
