Improve scripts

diff --git a/bin/brightness b/bin/brightness
--- a/bin/brightness
+++ b/bin/brightness
@@ -1,7 +1,14 @@
 #!/bin/sh -eu
-
+# Simple brightness control.
+#
 # Partially "borrowed" from Bob Hepple.
 # Licensed GPLv3(?), see https://gitlab.com/wef/dotfiles/-/blob/master/bin/brightness
+
+usage() {
+  echo "Usage: $0 <percent/+percent/-percent/up/down/off>"
+  echo
+  exit 0
+}
 
 class="/sys/class/backlight"
 handler=$class/$(ls $class | head -n 1)
@@ -12,11 +19,7 @@ current_brightness_p=$(( 100 * $current_brightness / $max_brightness ))
 new_brightness=
 new_brightness_p=
 
-[ $max_brightness -gt 0 ] || {
-  echo >&2 "Error: max brightness cannot be 0 or lower."
-  echo >&2 
-  exit 1
-}
+[ $max_brightness -gt 0 ] || err "Error: max brightness cannot be 0 or lower."
 
 set_brightness() {
   case "$1" in
@@ -60,15 +63,12 @@ set_brightness() {
   echo $new_brightness | doas tee $handler"/brightness" > /dev/null
 }
 
-value=${1:-0}
-
-case $value in
-  -h|--help)
-      echo "Usage: $0 <percent/+percent/-percent/up/down/off>"
-      echo
+case "${1:-}" in
+  ""|-h|--help)
+    usage 
     ;;
   *)
-    set_brightness $value
+    set_brightness $1
     ;;
 esac
 
diff --git a/bin/netcat b/bin/netcat
--- a/bin/netcat
+++ b/bin/netcat
@@ -1,17 +1,16 @@
 #!/bin/sh -eu
 
-command -v curl >/dev/null 2>&1 || { 
-    echo >&2 "Error: curl is required but not installed. Aborting."
-    echo >&2 
-    exit 1
+required curl
+
+usage() {
+    echo "Usage: $0 <URL>"
+    echo
+    exit 0
 }
 
-
-if [ $# -ne 1 ]; then
-    echo >&2 "Usage: $0 <URL>"
-    echo >&2
-    exit 1
-fi
+case "${1:-}" in
+    ""|-h|--help) usage ;;
+esac
 
 cache_directory="${XDG_CACHE_HOME:-"$HOME/.cache"}/netcat"
 cache_path="$cache_directory/$(echo "$1" | md5sum | awk '{print $1}')"
@@ -30,9 +29,4 @@ else
     curl "$1" -o "$cache_path" > /dev/null 2>&1 
 fi
 
-[ -e "$cache_path" ] && cat "$cache_path" || {
-    echo >&2 "Error: downloading file failed and local copy doesn't exist."
-    echo >&2 
-    exit 1
-}
-
+[ -e "$cache_path" ] && cat "$cache_path" || err "downloading file failed and local copy doesn't exist"
diff --git a/bin/prompt b/bin/prompt
--- a/bin/prompt
+++ b/bin/prompt
@@ -1,16 +1,21 @@
-#!/bin/sh
+#!/bin/sh -eu
+# Confirmation prompt for use in scripts.
+
+usage() {
+  echo "Usage: $0 <opt> <prompt>"
+  echo
+  echo "OPTIONS"
+  echo "  -y          Make 'Yes' the primary option."
+  echo "  -n          Make 'No' the primary option."
+  echo "  -h, --help  Show this help."
+  exit 0
+}
 
 [ -n "$2" ] && prompt="$2 "
 
-case "$1" in
-  -h|--help)
-    echo "Usage: $0 <opt> <prompt>"
-    echo
-    echo "OPTIONS"
-    echo "  -y          Make 'Yes' the primary option."
-    echo "  -n          Make 'No' the primary option."
-    echo "  -h, --help  Show this help."
-    exit 0
+case "${1:-}" in
+  ""|-h|--help)
+    usage
     ;;
   -y)
     opts="[Y/n]"
@@ -21,9 +26,7 @@ case "$1" in
     exit_c=1
     ;;
   *)
-    echo >&2 "Error: invalid option. Expected either -y or -n."
-    echo >&2 "Try --help for a summary of all options."
-    exit 1
+    err "invalid option. Expected either -y or -n."
 esac
 
 printf "$prompt$opts "
@@ -31,13 +34,12 @@ read yn </dev/tty
 
 case "$yn" in
     [yY]|[yY][eE][sS]) 
-        exit 0
-        ;;
+      exit 0
+      ;;
     [nN]|[nN][oO])
-        exit 1 
-        ;;
+      exit 1 
+      ;;
     *)
-        exit $exit_c
-        ;;
+      exit $exit_c
+      ;;
 esac
-
