Sync

diff --git a/bin/brightness b/bin/brightness
--- a/bin/brightness
+++ b/bin/brightness
@@ -12,8 +12,11 @@ current_brightness_p=$(( 100 * $current_brightness / $max_brightness ))
 new_brightness=
 new_brightness_p=
 
-[ $max_brightness -gt 0 ] ||
-  (printf "Error: max brightness cannot be 0 or lower.\n\n" && exit 1)
+[ $max_brightness -gt 0 ] || {
+  echo >&2 "Error: max brightness cannot be 0 or lower."
+  echo >&2 
+  exit 1
+}
 
 set_brightness() {
   case "$1" in
diff --git a/bin/netcat b/bin/netcat
--- a/bin/netcat
+++ b/bin/netcat
@@ -1,17 +1,24 @@
 #!/bin/sh -eu
 
+command -v curl >/dev/null 2>&1 || { 
+    echo >&2 "Error: curl is required but not installed. Aborting."
+    echo >&2 
+    exit 1
+}
+
+
 hash() {
     echo -n "$1" | md5sum | awk '{print $1}'
 }
 
-cache_directory="${XDG_CACHE_HOME:-"$HOME/.cache"}/netcat"
-cache_path="$cache_directory/$(hash "$1")"
-
 if [ $# -ne 1 ]; then
-    echo "Usage: $0 <URL>"
-    echo
+    echo >&2 "Usage: $0 <URL>"
+    echo >&2
     exit 1
 fi
+
+cache_directory="${XDG_CACHE_HOME:-"$HOME/.cache"}/netcat"
+cache_path="$cache_directory/$(hash "$1")"
 
 if [ -e "$cache_path" -a -z "${REFETCH:-}" ]; then
     last_mod=$(date -r "$cache_path" +%s)
@@ -28,8 +35,8 @@ else
 fi
 
 [ -e "$cache_path" ] && cat "$cache_path" || {
-    echo "Error: Downloading file failed and local copy doesn't exist."
-    echo
+    echo >&2 "Error: downloading file failed and local copy doesn't exist."
+    echo >&2 
     exit 1
 }
 
diff --git a/bin/prompt b/bin/prompt
--- a/bin/prompt
+++ b/bin/prompt
@@ -21,8 +21,8 @@ case "$1" in
     exit_c=1
     ;;
   *)
-    echo "Error: invalid option. Expected either -y or -n."
-    echo "Try --help for a summary of all options."
+    echo >&2 "Error: invalid option. Expected either -y or -n."
+    echo >&2 "Try --help for a summary of all options."
     exit 1
 esac
 
